spring.application.name=ehip-backend
server.port=8080

spring.profiles.active=local

#projectehip.database.windows.net
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

logging.level.root=INFO
logging.level.com.healthcare.cdss=DEBUG
logging.file.name=app.log

#Hibernate auto-updates tables
#SQL queries printed in console
#SQLsyntax generated for SQL Server
